// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RectangleSearch.Data;

#nullable disable

namespace RectangleSearch.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231026181417_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("RectangleSearch.Models.Rectangle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rectangles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 2,
                            Width = 2,
                            X = 3,
                            Y = 4
                        },
                        new
                        {
                            Id = 2,
                            Height = 4,
                            Width = 4,
                            X = 6,
                            Y = 8
                        },
                        new
                        {
                            Id = 3,
                            Height = 6,
                            Width = 6,
                            X = 9,
                            Y = 12
                        },
                        new
                        {
                            Id = 4,
                            Height = 8,
                            Width = 8,
                            X = 12,
                            Y = 16
                        },
                        new
                        {
                            Id = 5,
                            Height = 10,
                            Width = 10,
                            X = 15,
                            Y = 20
                        },
                        new
                        {
                            Id = 6,
                            Height = 12,
                            Width = 12,
                            X = 18,
                            Y = 24
                        },
                        new
                        {
                            Id = 7,
                            Height = 14,
                            Width = 14,
                            X = 21,
                            Y = 28
                        },
                        new
                        {
                            Id = 8,
                            Height = 16,
                            Width = 16,
                            X = 24,
                            Y = 32
                        },
                        new
                        {
                            Id = 9,
                            Height = 18,
                            Width = 18,
                            X = 27,
                            Y = 36
                        },
                        new
                        {
                            Id = 10,
                            Height = 20,
                            Width = 20,
                            X = 30,
                            Y = 40
                        },
                        new
                        {
                            Id = 11,
                            Height = 22,
                            Width = 22,
                            X = 33,
                            Y = 44
                        },
                        new
                        {
                            Id = 12,
                            Height = 24,
                            Width = 24,
                            X = 36,
                            Y = 48
                        },
                        new
                        {
                            Id = 13,
                            Height = 26,
                            Width = 26,
                            X = 39,
                            Y = 52
                        },
                        new
                        {
                            Id = 14,
                            Height = 28,
                            Width = 28,
                            X = 42,
                            Y = 56
                        },
                        new
                        {
                            Id = 15,
                            Height = 30,
                            Width = 30,
                            X = 45,
                            Y = 60
                        },
                        new
                        {
                            Id = 16,
                            Height = 32,
                            Width = 32,
                            X = 48,
                            Y = 64
                        },
                        new
                        {
                            Id = 17,
                            Height = 34,
                            Width = 34,
                            X = 51,
                            Y = 68
                        },
                        new
                        {
                            Id = 18,
                            Height = 36,
                            Width = 36,
                            X = 54,
                            Y = 72
                        },
                        new
                        {
                            Id = 19,
                            Height = 38,
                            Width = 38,
                            X = 57,
                            Y = 76
                        },
                        new
                        {
                            Id = 20,
                            Height = 40,
                            Width = 40,
                            X = 60,
                            Y = 80
                        },
                        new
                        {
                            Id = 21,
                            Height = 42,
                            Width = 42,
                            X = 63,
                            Y = 84
                        },
                        new
                        {
                            Id = 22,
                            Height = 44,
                            Width = 44,
                            X = 66,
                            Y = 88
                        },
                        new
                        {
                            Id = 23,
                            Height = 46,
                            Width = 46,
                            X = 69,
                            Y = 92
                        },
                        new
                        {
                            Id = 24,
                            Height = 48,
                            Width = 48,
                            X = 72,
                            Y = 96
                        },
                        new
                        {
                            Id = 25,
                            Height = 50,
                            Width = 50,
                            X = 75,
                            Y = 100
                        },
                        new
                        {
                            Id = 26,
                            Height = 52,
                            Width = 52,
                            X = 78,
                            Y = 104
                        },
                        new
                        {
                            Id = 27,
                            Height = 54,
                            Width = 54,
                            X = 81,
                            Y = 108
                        },
                        new
                        {
                            Id = 28,
                            Height = 56,
                            Width = 56,
                            X = 84,
                            Y = 112
                        },
                        new
                        {
                            Id = 29,
                            Height = 58,
                            Width = 58,
                            X = 87,
                            Y = 116
                        },
                        new
                        {
                            Id = 30,
                            Height = 60,
                            Width = 60,
                            X = 90,
                            Y = 120
                        },
                        new
                        {
                            Id = 31,
                            Height = 62,
                            Width = 62,
                            X = 93,
                            Y = 124
                        },
                        new
                        {
                            Id = 32,
                            Height = 64,
                            Width = 64,
                            X = 96,
                            Y = 128
                        },
                        new
                        {
                            Id = 33,
                            Height = 66,
                            Width = 66,
                            X = 99,
                            Y = 132
                        },
                        new
                        {
                            Id = 34,
                            Height = 68,
                            Width = 68,
                            X = 102,
                            Y = 136
                        },
                        new
                        {
                            Id = 35,
                            Height = 70,
                            Width = 70,
                            X = 105,
                            Y = 140
                        },
                        new
                        {
                            Id = 36,
                            Height = 72,
                            Width = 72,
                            X = 108,
                            Y = 144
                        },
                        new
                        {
                            Id = 37,
                            Height = 74,
                            Width = 74,
                            X = 111,
                            Y = 148
                        },
                        new
                        {
                            Id = 38,
                            Height = 76,
                            Width = 76,
                            X = 114,
                            Y = 152
                        },
                        new
                        {
                            Id = 39,
                            Height = 78,
                            Width = 78,
                            X = 117,
                            Y = 156
                        },
                        new
                        {
                            Id = 40,
                            Height = 80,
                            Width = 80,
                            X = 120,
                            Y = 160
                        },
                        new
                        {
                            Id = 41,
                            Height = 82,
                            Width = 82,
                            X = 123,
                            Y = 164
                        },
                        new
                        {
                            Id = 42,
                            Height = 84,
                            Width = 84,
                            X = 126,
                            Y = 168
                        },
                        new
                        {
                            Id = 43,
                            Height = 86,
                            Width = 86,
                            X = 129,
                            Y = 172
                        },
                        new
                        {
                            Id = 44,
                            Height = 88,
                            Width = 88,
                            X = 132,
                            Y = 176
                        },
                        new
                        {
                            Id = 45,
                            Height = 90,
                            Width = 90,
                            X = 135,
                            Y = 180
                        },
                        new
                        {
                            Id = 46,
                            Height = 92,
                            Width = 92,
                            X = 138,
                            Y = 184
                        },
                        new
                        {
                            Id = 47,
                            Height = 94,
                            Width = 94,
                            X = 141,
                            Y = 188
                        },
                        new
                        {
                            Id = 48,
                            Height = 96,
                            Width = 96,
                            X = 144,
                            Y = 192
                        },
                        new
                        {
                            Id = 49,
                            Height = 98,
                            Width = 98,
                            X = 147,
                            Y = 196
                        },
                        new
                        {
                            Id = 50,
                            Height = 100,
                            Width = 100,
                            X = 150,
                            Y = 200
                        },
                        new
                        {
                            Id = 51,
                            Height = 102,
                            Width = 102,
                            X = 153,
                            Y = 204
                        },
                        new
                        {
                            Id = 52,
                            Height = 104,
                            Width = 104,
                            X = 156,
                            Y = 208
                        },
                        new
                        {
                            Id = 53,
                            Height = 106,
                            Width = 106,
                            X = 159,
                            Y = 212
                        },
                        new
                        {
                            Id = 54,
                            Height = 108,
                            Width = 108,
                            X = 162,
                            Y = 216
                        },
                        new
                        {
                            Id = 55,
                            Height = 110,
                            Width = 110,
                            X = 165,
                            Y = 220
                        },
                        new
                        {
                            Id = 56,
                            Height = 112,
                            Width = 112,
                            X = 168,
                            Y = 224
                        },
                        new
                        {
                            Id = 57,
                            Height = 114,
                            Width = 114,
                            X = 171,
                            Y = 228
                        },
                        new
                        {
                            Id = 58,
                            Height = 116,
                            Width = 116,
                            X = 174,
                            Y = 232
                        },
                        new
                        {
                            Id = 59,
                            Height = 118,
                            Width = 118,
                            X = 177,
                            Y = 236
                        },
                        new
                        {
                            Id = 60,
                            Height = 120,
                            Width = 120,
                            X = 180,
                            Y = 240
                        },
                        new
                        {
                            Id = 61,
                            Height = 122,
                            Width = 122,
                            X = 183,
                            Y = 244
                        },
                        new
                        {
                            Id = 62,
                            Height = 124,
                            Width = 124,
                            X = 186,
                            Y = 248
                        },
                        new
                        {
                            Id = 63,
                            Height = 126,
                            Width = 126,
                            X = 189,
                            Y = 252
                        },
                        new
                        {
                            Id = 64,
                            Height = 128,
                            Width = 128,
                            X = 192,
                            Y = 256
                        },
                        new
                        {
                            Id = 65,
                            Height = 130,
                            Width = 130,
                            X = 195,
                            Y = 260
                        },
                        new
                        {
                            Id = 66,
                            Height = 132,
                            Width = 132,
                            X = 198,
                            Y = 264
                        },
                        new
                        {
                            Id = 67,
                            Height = 134,
                            Width = 134,
                            X = 201,
                            Y = 268
                        },
                        new
                        {
                            Id = 68,
                            Height = 136,
                            Width = 136,
                            X = 204,
                            Y = 272
                        },
                        new
                        {
                            Id = 69,
                            Height = 138,
                            Width = 138,
                            X = 207,
                            Y = 276
                        },
                        new
                        {
                            Id = 70,
                            Height = 140,
                            Width = 140,
                            X = 210,
                            Y = 280
                        },
                        new
                        {
                            Id = 71,
                            Height = 142,
                            Width = 142,
                            X = 213,
                            Y = 284
                        },
                        new
                        {
                            Id = 72,
                            Height = 144,
                            Width = 144,
                            X = 216,
                            Y = 288
                        },
                        new
                        {
                            Id = 73,
                            Height = 146,
                            Width = 146,
                            X = 219,
                            Y = 292
                        },
                        new
                        {
                            Id = 74,
                            Height = 148,
                            Width = 148,
                            X = 222,
                            Y = 296
                        },
                        new
                        {
                            Id = 75,
                            Height = 150,
                            Width = 150,
                            X = 225,
                            Y = 300
                        },
                        new
                        {
                            Id = 76,
                            Height = 152,
                            Width = 152,
                            X = 228,
                            Y = 304
                        },
                        new
                        {
                            Id = 77,
                            Height = 154,
                            Width = 154,
                            X = 231,
                            Y = 308
                        },
                        new
                        {
                            Id = 78,
                            Height = 156,
                            Width = 156,
                            X = 234,
                            Y = 312
                        },
                        new
                        {
                            Id = 79,
                            Height = 158,
                            Width = 158,
                            X = 237,
                            Y = 316
                        },
                        new
                        {
                            Id = 80,
                            Height = 160,
                            Width = 160,
                            X = 240,
                            Y = 320
                        },
                        new
                        {
                            Id = 81,
                            Height = 162,
                            Width = 162,
                            X = 243,
                            Y = 324
                        },
                        new
                        {
                            Id = 82,
                            Height = 164,
                            Width = 164,
                            X = 246,
                            Y = 328
                        },
                        new
                        {
                            Id = 83,
                            Height = 166,
                            Width = 166,
                            X = 249,
                            Y = 332
                        },
                        new
                        {
                            Id = 84,
                            Height = 168,
                            Width = 168,
                            X = 252,
                            Y = 336
                        },
                        new
                        {
                            Id = 85,
                            Height = 170,
                            Width = 170,
                            X = 255,
                            Y = 340
                        },
                        new
                        {
                            Id = 86,
                            Height = 172,
                            Width = 172,
                            X = 258,
                            Y = 344
                        },
                        new
                        {
                            Id = 87,
                            Height = 174,
                            Width = 174,
                            X = 261,
                            Y = 348
                        },
                        new
                        {
                            Id = 88,
                            Height = 176,
                            Width = 176,
                            X = 264,
                            Y = 352
                        },
                        new
                        {
                            Id = 89,
                            Height = 178,
                            Width = 178,
                            X = 267,
                            Y = 356
                        },
                        new
                        {
                            Id = 90,
                            Height = 180,
                            Width = 180,
                            X = 270,
                            Y = 360
                        },
                        new
                        {
                            Id = 91,
                            Height = 182,
                            Width = 182,
                            X = 273,
                            Y = 364
                        },
                        new
                        {
                            Id = 92,
                            Height = 184,
                            Width = 184,
                            X = 276,
                            Y = 368
                        },
                        new
                        {
                            Id = 93,
                            Height = 186,
                            Width = 186,
                            X = 279,
                            Y = 372
                        },
                        new
                        {
                            Id = 94,
                            Height = 188,
                            Width = 188,
                            X = 282,
                            Y = 376
                        },
                        new
                        {
                            Id = 95,
                            Height = 190,
                            Width = 190,
                            X = 285,
                            Y = 380
                        },
                        new
                        {
                            Id = 96,
                            Height = 192,
                            Width = 192,
                            X = 288,
                            Y = 384
                        },
                        new
                        {
                            Id = 97,
                            Height = 194,
                            Width = 194,
                            X = 291,
                            Y = 388
                        },
                        new
                        {
                            Id = 98,
                            Height = 196,
                            Width = 196,
                            X = 294,
                            Y = 392
                        },
                        new
                        {
                            Id = 99,
                            Height = 198,
                            Width = 198,
                            X = 297,
                            Y = 396
                        },
                        new
                        {
                            Id = 100,
                            Height = 200,
                            Width = 200,
                            X = 300,
                            Y = 400
                        },
                        new
                        {
                            Id = 101,
                            Height = 202,
                            Width = 202,
                            X = 303,
                            Y = 404
                        },
                        new
                        {
                            Id = 102,
                            Height = 204,
                            Width = 204,
                            X = 306,
                            Y = 408
                        },
                        new
                        {
                            Id = 103,
                            Height = 206,
                            Width = 206,
                            X = 309,
                            Y = 412
                        },
                        new
                        {
                            Id = 104,
                            Height = 208,
                            Width = 208,
                            X = 312,
                            Y = 416
                        },
                        new
                        {
                            Id = 105,
                            Height = 210,
                            Width = 210,
                            X = 315,
                            Y = 420
                        },
                        new
                        {
                            Id = 106,
                            Height = 212,
                            Width = 212,
                            X = 318,
                            Y = 424
                        },
                        new
                        {
                            Id = 107,
                            Height = 214,
                            Width = 214,
                            X = 321,
                            Y = 428
                        },
                        new
                        {
                            Id = 108,
                            Height = 216,
                            Width = 216,
                            X = 324,
                            Y = 432
                        },
                        new
                        {
                            Id = 109,
                            Height = 218,
                            Width = 218,
                            X = 327,
                            Y = 436
                        },
                        new
                        {
                            Id = 110,
                            Height = 220,
                            Width = 220,
                            X = 330,
                            Y = 440
                        },
                        new
                        {
                            Id = 111,
                            Height = 222,
                            Width = 222,
                            X = 333,
                            Y = 444
                        },
                        new
                        {
                            Id = 112,
                            Height = 224,
                            Width = 224,
                            X = 336,
                            Y = 448
                        },
                        new
                        {
                            Id = 113,
                            Height = 226,
                            Width = 226,
                            X = 339,
                            Y = 452
                        },
                        new
                        {
                            Id = 114,
                            Height = 228,
                            Width = 228,
                            X = 342,
                            Y = 456
                        },
                        new
                        {
                            Id = 115,
                            Height = 230,
                            Width = 230,
                            X = 345,
                            Y = 460
                        },
                        new
                        {
                            Id = 116,
                            Height = 232,
                            Width = 232,
                            X = 348,
                            Y = 464
                        },
                        new
                        {
                            Id = 117,
                            Height = 234,
                            Width = 234,
                            X = 351,
                            Y = 468
                        },
                        new
                        {
                            Id = 118,
                            Height = 236,
                            Width = 236,
                            X = 354,
                            Y = 472
                        },
                        new
                        {
                            Id = 119,
                            Height = 238,
                            Width = 238,
                            X = 357,
                            Y = 476
                        },
                        new
                        {
                            Id = 120,
                            Height = 240,
                            Width = 240,
                            X = 360,
                            Y = 480
                        },
                        new
                        {
                            Id = 121,
                            Height = 242,
                            Width = 242,
                            X = 363,
                            Y = 484
                        },
                        new
                        {
                            Id = 122,
                            Height = 244,
                            Width = 244,
                            X = 366,
                            Y = 488
                        },
                        new
                        {
                            Id = 123,
                            Height = 246,
                            Width = 246,
                            X = 369,
                            Y = 492
                        },
                        new
                        {
                            Id = 124,
                            Height = 248,
                            Width = 248,
                            X = 372,
                            Y = 496
                        },
                        new
                        {
                            Id = 125,
                            Height = 250,
                            Width = 250,
                            X = 375,
                            Y = 500
                        },
                        new
                        {
                            Id = 126,
                            Height = 252,
                            Width = 252,
                            X = 378,
                            Y = 504
                        },
                        new
                        {
                            Id = 127,
                            Height = 254,
                            Width = 254,
                            X = 381,
                            Y = 508
                        },
                        new
                        {
                            Id = 128,
                            Height = 256,
                            Width = 256,
                            X = 384,
                            Y = 512
                        },
                        new
                        {
                            Id = 129,
                            Height = 258,
                            Width = 258,
                            X = 387,
                            Y = 516
                        },
                        new
                        {
                            Id = 130,
                            Height = 260,
                            Width = 260,
                            X = 390,
                            Y = 520
                        },
                        new
                        {
                            Id = 131,
                            Height = 262,
                            Width = 262,
                            X = 393,
                            Y = 524
                        },
                        new
                        {
                            Id = 132,
                            Height = 264,
                            Width = 264,
                            X = 396,
                            Y = 528
                        },
                        new
                        {
                            Id = 133,
                            Height = 266,
                            Width = 266,
                            X = 399,
                            Y = 532
                        },
                        new
                        {
                            Id = 134,
                            Height = 268,
                            Width = 268,
                            X = 402,
                            Y = 536
                        },
                        new
                        {
                            Id = 135,
                            Height = 270,
                            Width = 270,
                            X = 405,
                            Y = 540
                        },
                        new
                        {
                            Id = 136,
                            Height = 272,
                            Width = 272,
                            X = 408,
                            Y = 544
                        },
                        new
                        {
                            Id = 137,
                            Height = 274,
                            Width = 274,
                            X = 411,
                            Y = 548
                        },
                        new
                        {
                            Id = 138,
                            Height = 276,
                            Width = 276,
                            X = 414,
                            Y = 552
                        },
                        new
                        {
                            Id = 139,
                            Height = 278,
                            Width = 278,
                            X = 417,
                            Y = 556
                        },
                        new
                        {
                            Id = 140,
                            Height = 280,
                            Width = 280,
                            X = 420,
                            Y = 560
                        },
                        new
                        {
                            Id = 141,
                            Height = 282,
                            Width = 282,
                            X = 423,
                            Y = 564
                        },
                        new
                        {
                            Id = 142,
                            Height = 284,
                            Width = 284,
                            X = 426,
                            Y = 568
                        },
                        new
                        {
                            Id = 143,
                            Height = 286,
                            Width = 286,
                            X = 429,
                            Y = 572
                        },
                        new
                        {
                            Id = 144,
                            Height = 288,
                            Width = 288,
                            X = 432,
                            Y = 576
                        },
                        new
                        {
                            Id = 145,
                            Height = 290,
                            Width = 290,
                            X = 435,
                            Y = 580
                        },
                        new
                        {
                            Id = 146,
                            Height = 292,
                            Width = 292,
                            X = 438,
                            Y = 584
                        },
                        new
                        {
                            Id = 147,
                            Height = 294,
                            Width = 294,
                            X = 441,
                            Y = 588
                        },
                        new
                        {
                            Id = 148,
                            Height = 296,
                            Width = 296,
                            X = 444,
                            Y = 592
                        },
                        new
                        {
                            Id = 149,
                            Height = 298,
                            Width = 298,
                            X = 447,
                            Y = 596
                        },
                        new
                        {
                            Id = 150,
                            Height = 300,
                            Width = 300,
                            X = 450,
                            Y = 600
                        },
                        new
                        {
                            Id = 151,
                            Height = 302,
                            Width = 302,
                            X = 453,
                            Y = 604
                        },
                        new
                        {
                            Id = 152,
                            Height = 304,
                            Width = 304,
                            X = 456,
                            Y = 608
                        },
                        new
                        {
                            Id = 153,
                            Height = 306,
                            Width = 306,
                            X = 459,
                            Y = 612
                        },
                        new
                        {
                            Id = 154,
                            Height = 308,
                            Width = 308,
                            X = 462,
                            Y = 616
                        },
                        new
                        {
                            Id = 155,
                            Height = 310,
                            Width = 310,
                            X = 465,
                            Y = 620
                        },
                        new
                        {
                            Id = 156,
                            Height = 312,
                            Width = 312,
                            X = 468,
                            Y = 624
                        },
                        new
                        {
                            Id = 157,
                            Height = 314,
                            Width = 314,
                            X = 471,
                            Y = 628
                        },
                        new
                        {
                            Id = 158,
                            Height = 316,
                            Width = 316,
                            X = 474,
                            Y = 632
                        },
                        new
                        {
                            Id = 159,
                            Height = 318,
                            Width = 318,
                            X = 477,
                            Y = 636
                        },
                        new
                        {
                            Id = 160,
                            Height = 320,
                            Width = 320,
                            X = 480,
                            Y = 640
                        },
                        new
                        {
                            Id = 161,
                            Height = 322,
                            Width = 322,
                            X = 483,
                            Y = 644
                        },
                        new
                        {
                            Id = 162,
                            Height = 324,
                            Width = 324,
                            X = 486,
                            Y = 648
                        },
                        new
                        {
                            Id = 163,
                            Height = 326,
                            Width = 326,
                            X = 489,
                            Y = 652
                        },
                        new
                        {
                            Id = 164,
                            Height = 328,
                            Width = 328,
                            X = 492,
                            Y = 656
                        },
                        new
                        {
                            Id = 165,
                            Height = 330,
                            Width = 330,
                            X = 495,
                            Y = 660
                        },
                        new
                        {
                            Id = 166,
                            Height = 332,
                            Width = 332,
                            X = 498,
                            Y = 664
                        },
                        new
                        {
                            Id = 167,
                            Height = 334,
                            Width = 334,
                            X = 501,
                            Y = 668
                        },
                        new
                        {
                            Id = 168,
                            Height = 336,
                            Width = 336,
                            X = 504,
                            Y = 672
                        },
                        new
                        {
                            Id = 169,
                            Height = 338,
                            Width = 338,
                            X = 507,
                            Y = 676
                        },
                        new
                        {
                            Id = 170,
                            Height = 340,
                            Width = 340,
                            X = 510,
                            Y = 680
                        },
                        new
                        {
                            Id = 171,
                            Height = 342,
                            Width = 342,
                            X = 513,
                            Y = 684
                        },
                        new
                        {
                            Id = 172,
                            Height = 344,
                            Width = 344,
                            X = 516,
                            Y = 688
                        },
                        new
                        {
                            Id = 173,
                            Height = 346,
                            Width = 346,
                            X = 519,
                            Y = 692
                        },
                        new
                        {
                            Id = 174,
                            Height = 348,
                            Width = 348,
                            X = 522,
                            Y = 696
                        },
                        new
                        {
                            Id = 175,
                            Height = 350,
                            Width = 350,
                            X = 525,
                            Y = 700
                        },
                        new
                        {
                            Id = 176,
                            Height = 352,
                            Width = 352,
                            X = 528,
                            Y = 704
                        },
                        new
                        {
                            Id = 177,
                            Height = 354,
                            Width = 354,
                            X = 531,
                            Y = 708
                        },
                        new
                        {
                            Id = 178,
                            Height = 356,
                            Width = 356,
                            X = 534,
                            Y = 712
                        },
                        new
                        {
                            Id = 179,
                            Height = 358,
                            Width = 358,
                            X = 537,
                            Y = 716
                        },
                        new
                        {
                            Id = 180,
                            Height = 360,
                            Width = 360,
                            X = 540,
                            Y = 720
                        },
                        new
                        {
                            Id = 181,
                            Height = 362,
                            Width = 362,
                            X = 543,
                            Y = 724
                        },
                        new
                        {
                            Id = 182,
                            Height = 364,
                            Width = 364,
                            X = 546,
                            Y = 728
                        },
                        new
                        {
                            Id = 183,
                            Height = 366,
                            Width = 366,
                            X = 549,
                            Y = 732
                        },
                        new
                        {
                            Id = 184,
                            Height = 368,
                            Width = 368,
                            X = 552,
                            Y = 736
                        },
                        new
                        {
                            Id = 185,
                            Height = 370,
                            Width = 370,
                            X = 555,
                            Y = 740
                        },
                        new
                        {
                            Id = 186,
                            Height = 372,
                            Width = 372,
                            X = 558,
                            Y = 744
                        },
                        new
                        {
                            Id = 187,
                            Height = 374,
                            Width = 374,
                            X = 561,
                            Y = 748
                        },
                        new
                        {
                            Id = 188,
                            Height = 376,
                            Width = 376,
                            X = 564,
                            Y = 752
                        },
                        new
                        {
                            Id = 189,
                            Height = 378,
                            Width = 378,
                            X = 567,
                            Y = 756
                        },
                        new
                        {
                            Id = 190,
                            Height = 380,
                            Width = 380,
                            X = 570,
                            Y = 760
                        },
                        new
                        {
                            Id = 191,
                            Height = 382,
                            Width = 382,
                            X = 573,
                            Y = 764
                        },
                        new
                        {
                            Id = 192,
                            Height = 384,
                            Width = 384,
                            X = 576,
                            Y = 768
                        },
                        new
                        {
                            Id = 193,
                            Height = 386,
                            Width = 386,
                            X = 579,
                            Y = 772
                        },
                        new
                        {
                            Id = 194,
                            Height = 388,
                            Width = 388,
                            X = 582,
                            Y = 776
                        },
                        new
                        {
                            Id = 195,
                            Height = 390,
                            Width = 390,
                            X = 585,
                            Y = 780
                        },
                        new
                        {
                            Id = 196,
                            Height = 392,
                            Width = 392,
                            X = 588,
                            Y = 784
                        },
                        new
                        {
                            Id = 197,
                            Height = 394,
                            Width = 394,
                            X = 591,
                            Y = 788
                        },
                        new
                        {
                            Id = 198,
                            Height = 396,
                            Width = 396,
                            X = 594,
                            Y = 792
                        },
                        new
                        {
                            Id = 199,
                            Height = 398,
                            Width = 398,
                            X = 597,
                            Y = 796
                        },
                        new
                        {
                            Id = 200,
                            Height = 400,
                            Width = 400,
                            X = 600,
                            Y = 800
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
